### ISSUE TITLE
Auto-Index!

### ISSUE THREAD

**Issue by jrmann100** [jrmann100/kentSearch#2]
Popup.js currently _defines_ classes/their ID's– it should grab them from the directory to keep itself updated. Auto-indexing was is only reason the dropdown was implemented.

**Comment by broad-well** [comment]
I noted in the .js file that autoindex is expected in future updates. A possible solution is to use a server to do it.

**Comment by jrmann100** [comment]
Yep. I'll look into other possible solutions.

**Comment by broad-well** [comment]
Auto-index not plausible for Edline.
