### ISSUE TITLE
Class referencing by class code

### ISSUE THREAD

**Issue by broad-well** [jrmann100/kentSearch#23]
It would be a good idea to be able to type the class code _(`SPANB`, for example)_ into the search box and get to the class page immediately. Right now, the user has to click on the autocomplete suggestion before submitting their search query in order to get a successful redirection.

**Comment by jrmann100** [comment]
LIke it. I don't quite understand Semantic, but you being the wizard should help.

**Comment by broad-well** [comment]
The commit above resolves this issue.
