### ISSUE TITLE
Selection is Dysfunctional

### ISSUE THREAD

**Issue by jrmann100** [jrmann100/kentSearch#3]
As of today, the selection of class entry is not working. We need to fix _immediately._

**Comment by jrmann100** [comment]
Um, no. It's actually not working.

**Comment by broad-well** [comment]
I will update the `for` loop (the modern syntax) today. It works in OS X Mountain Lion.
Library computers do not support the 2015 ECMAScript standard.

**Comment by broad-well** [comment]
Working correctly. The original `let` syntax was not supported outside strict mode.
