### ISSUE TITLE
Not quite working...

### ISSUE THREAD

**Issue by jrmann100** [jrmann100/kentSearch#4]
KentSearch isn't registering my correct text entry... I'm not sure why yet, but I will look!

**Comment by broad-well** [comment]
What was your textentry content?

**Comment by jrmann100** [comment]
Ahm... "sci7". Just try anything.

**Comment by broad-well** [comment]
It only allows uppercase characters. I am going to change the verification mechanism and ignore caps. (Unix-like web servers are case-sensitive)

**Comment by jrmann100** [comment]
Got it. That was kind of scary!

**Comment by jrmann100** [comment]
And you know what? It wouldn't have mattered. Edline's down.

We might want to start thinking about making this adaptable for any search template… (example: save your logo as "icon.png" and it changes all the icons)
