### ISSUE TITLE
Errors!

### ISSUE THREAD

**Issue by jrmann100** [jrmann100/kentSearch#7]
The error dialog should close after a new, correct query is entered. This can most likely be done with the onSearchQuery callback (see popup.js, line 87).

**Comment by jrmann100** [comment]
It doesn't really matter, actually.

**Comment by jrmann100** [comment]
What _does_ matter is that KS loads smoothly. If possible, the new tab page's search bar should be hidden until all files (css, js) are loaded.

I will work on this.

**Comment by broad-well** [comment]
Unfortunately I already have a working commit. `7b08bd5ea78e549a3b8b4e82480e3c9d01f7cb83`
