### ISSUE TITLE
Something's quite wrong…

### ISSUE THREAD

**Issue by jrmann100** [jrmann100/kentSearch#9]
In restructuring the background.js file, or something else in the most recent commit, the entire extension is failing. I'll check this out more when I have time.

**Comment by broad-well** [comment]
It seems that `chrome.extension` API is not available in an injected `iframe`, and this problem was introduced when I migrated the class data to `background.js` and made it global _(because it is served to multiple endpoints)_. Proper **Message Passing** emitter and handler will solve this issue.

**Comment by broad-well** [comment]
Commit `61d9a4e` solved the issue.
